import fs from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { build } from 'esbuild'
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const result = await build({
  absWorkingDir: root, entryPoints: ['mcp-ui/main.jsx'], bundle: true, write: false,
  outfile: 'comicchat-ui.js', format: 'iife', platform: 'browser', target: 'es2022',
  jsx: 'automatic', minify: true, metafile: true, legalComments: 'none',
  define: { 'process.env.NODE_ENV': '"production"' },
  loader: { '.js': 'jsx', '.module.css': 'local-css' },
  alias: { 'next/router': path.join(root, 'mcp-ui/next-router.jsx'),
    'next/head': path.join(root, 'mcp-ui/next-head.jsx') },
})
const js = result.outputFiles.find(f => f.path.endsWith('.js')).text.replace(/<\/script/gi, '<\\/script')
const css = result.outputFiles.find(f => f.path.endsWith('.css'))?.text || ''
const html = '<!doctype html><html lang="en" dir="ltr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>ComicChat</title><style>' +
  css + '\nhtml,body,#root{min-height:560px}body{margin:0}</style></head><body><div id="root"></div><script>' + js + '</script></body></html>'
await fs.writeFile(path.join(root, 'supabase/functions/comicchat-mcp/ui.ts'),
  '// Generated by npm run plugin:build-ui from the existing website UI. Do not edit.\nexport const COMICCHAT_APP_HTML = ' + JSON.stringify(html) + '\n')
await fs.writeFile(path.join(root, 'mcp-ui/build-manifest.json'), JSON.stringify({ inputs: Object.keys(result.metafile.inputs), bytes: Buffer.byteLength(html) }, null, 2) + '\n')
console.log('ComicChat shared website UI bundled: ' + Buffer.byteLength(html) + ' bytes')
